### ISSUE TITLE
babel option clash

### ISSUE THREAD

**Issue by mkyas** [foleyj2/ru-thesis#24]
The document
```
\documentclass{rubook}
\usepackage{ruthesis}
\usepackage[german,english]{babel}

\begin{document}

\end{document}

```
fails to build since our class files already load babel. Thus, we cannot use the standard interface to add languages.

**Comment by foleyj2** [comment]
As discussed in Issue #33, switching to polyglossia and putting it explicitly in the main.tex in commit db112afb936ae1ee995a46ef9e6755b0deca4d8a
